### ISSUE TITLE
Dependencies for script registration

### ISSUE THREAD

**Issue by krogsgard** [thomasgriffin/New-Media-Image-Uploader#2]
Hey Thomas,

I think you need to add the depencies for 'media-upload' and 'media-views'  in your script registration. If the page doesn't already load these scripts from WP, the upload won't work. Also, we found we need to run the wp_enqueue_media function if the WYSIWYG isn't running elsewhere in the admin. The Modern Tribe image widget sets it up nicely:
http://plugins.svn.wordpress.org/image-widget/tags/4.0.4/image-widget.php

**Comment by thomasgriffin** [comment]
Two things:
1. 'media-views' is already listed as a dependency when the 'media-editor' script is invoked via `wp_enqueue_media`, so that is an unnecessary redundancy.
2. 'media-upload' is the legacy script used in the old thickbox stuff, so that is only necessary if you plan on supporting the old system. I don't really want to support the old system, but that's a useful comment those that do. :-P

**Comment by krogsgard** [comment]
Then I guess the revised request would be to just add wp_enqueue_media : ) All I know  is that without the WYSIWYG, we couldn't get it to work w/ your previous method. So it was just a heads up. Thanks!

**Comment by thomasgriffin** [comment]
`wp_enqueue_media` is in the plugin, L72 :-): https://github.com/thomasgriffin/New-Media-Image-Uploader/blob/master/tgm-new-media-plugin.php#L72

**Comment by krogsgard** [comment]
Okay, I'll rephrase:

We tried to use your code, and could not get it to work when there isn't a WYSISYG on the page : ) I'll leave it to you to dissect, but we got it working fine with the sample in the tribe plugin.

**Comment by thomasgriffin** [comment]
Ok - I'll have to test it out and see what is up then. Thanks for posting the issue!

**Comment by thomasgriffin** [comment]
I've built this into a custom plugin screen without any issues (and it did not have a WYSIWYG editor), so I'm going to close out this issue.
