### ISSUE TITLE
destination folder

### ISSUE THREAD

**Issue by pdewouters** [thomasgriffin/New-Media-Image-Uploader#3]
Hi Thomas

thanks for this code sample. I'm wondering if it's possible to define the destination folder, maybe a subfolder of the default uploads folder?
thanks

**Comment by thomasgriffin** [comment]
You can do that via filters outside of Backbone. Since the Backbone Model runs through WordPress, you have access to any filters provided to adjust the default uploads location in WordPress. You can use the global `$_REQUEST` var to test against what parameters are specified to ensure that it is only being filtered within your modal instance.
