### ISSUE TITLE
How to send to input if using frame: 'post' ?

### ISSUE THREAD

**Issue by turtlepod** [thomasgriffin/New-Media-Image-Uploader#6]
hi thomas,
thank you for this. awesome job.
btw, if using `frame:'post'` how can i send the url of the image to input field?

i try this but it didn't work:

``` javascript
tgm_media_frame.on('post', function(){
    // Grab our attachment selection and construct a JSON representation of the model.
    var media_attachment = tgm_media_frame.state().get('selection').first().toJSON();

    // Send the attachment URL to our custom input field via jQuery.
    $('#tgm-new-media-image').val(media_attachment.url);
});
```

thank you.

**Comment by thomasgriffin** [comment]
When using frame: 'post', it uses a completely different type of frame related to the post at hand. It is the same setup that TinyMCE uses to send images and other data to the editor. I have not worked with frame 'post' much since it was not required when I built this, so I'm not sure where to point you other than to the `media-views.js` and `media-models.js` files in the `wp-includes` folder.
